# Tell the parser more about this template.
# All keys are case-sensitive
meta:
  # List of allowed issue types
  types:
    - Feature Requests
    - Bug report
  # This will be shown on the top of the issue form
  tip:  For support questions, please use stackoverflow.

form:
  # All keys - except "meta" - will be considered as fields. There is only one
  # Type of fields; Text boxes. Text boxes support GFM.

  # A field may also has a help text (rendered as HTML placeholder).
  # Parentheses **Required**, but, will be stripped.
  Description: ( Provide help text )

  # Feature requests

  What is the motivation / use case for changing the behavior?:
    # Limit the visibility of this field to specific issue type
    for: feature requests

  # Bugs

  What is the current behavior?:
    for: bug report

  Steps to reproduce:
    for: bug report

  Minimal demo (if possible):
    # A field may has a description. Description text will be rendered as inline
    # Markdown
    # You may also write
    desc: >
      Use [plnkr](https://plnkr.co) or similar (you can use
      [this template](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5) as a
      starting point).
    for: bug report


  What is the expected behavior?:
    for: bug report

  Version:
    # You can also write help text as key
    help: You may run "cmd --version" and paste the output here
    for: bug report

  # Other
  Other information: >
    (e.g. detailed explanation, stacktraces, related issues, suggestions
    how to fix, links for us to have context, eg. stackoverflow, gitter,
    et
